import { CatalogProduct } from './catalog.models';

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: 1,
    title: 'Embutidora al Vacío VF 300',
    category: 'Maquinaria Alemana',
    subcategory: 'Embutidoras al Vacío',
    brand: 'Handtmann',
    origin: 'Alemania',
    condition: 'Usada',
    description: 'Con elevador para contenedores de 200L y alto desempeño para producción continua.',
    image: 'https://picsum.photos/seed/vf300/700/500',
    available: true,
    capacity: '10,000 kg/h',
    voltage: '380V',
    power: '7 kW',
    tags: ['embutidos', 'alta capacidad', 'vacío']
  },
  {
    id: 2,
    title: 'Embutidora al Vacío VF 200B',
    category: 'Maquinaria Alemana',
    subcategory: 'Embutidoras al Vacío',
    brand: 'Handtmann',
    origin: 'Alemania',
    condition: 'Usada',
    description: 'Incluye elevador de 200L, diseñada para líneas de embutidos de media-alta escala.',
    image: 'https://picsum.photos/seed/vf200b/700/500',
    available: true,
    capacity: 'Producción media-alta',
    voltage: '380V',
    power: '7 kW',
    tags: ['embutidos', 'vacío']
  },
  {
    id: 3,
    title: 'Embutidora al Vacío VF 100',
    category: 'Maquinaria Alemana',
    subcategory: 'Embutidoras al Vacío',
    brand: 'Handtmann',
    origin: 'Alemania',
    condition: 'Usada',
    description: 'Versión compacta para plantas con alta exigencia sanitaria y de rendimiento.',
    image: 'https://picsum.photos/seed/vf100/700/500',
    available: false,
    voltage: '380V - 400V',
    tags: ['embutidos', 'compacta']
  },
  {
    id: 4,
    title: 'Chuleteadora Modelo 2411',
    category: 'Maquinaria Alemana',
    subcategory: 'Corte',
    brand: 'Treif',
    origin: 'Alemania',
    condition: 'Usada',
    description: 'Cortes precisos para línea cárnica con alta repetibilidad y productividad.',
    image: 'https://picsum.photos/seed/treif2411/700/500',
    available: true,
    capacity: 'Banda entrada 210mm / salida 407mm',
    tags: ['corte', 'cárnico']
  },
  {
    id: 5,
    title: 'Sistema de Clipado FCA 3462',
    category: 'Maquinaria Alemana',
    subcategory: 'Clipado',
    brand: 'Poly-Clip',
    origin: 'Alemania',
    condition: 'Usada',
    description: 'Cortadora automática móvil con sistema Polyclip para cierre de embutidos.',
    image: 'https://picsum.photos/seed/fca3462/700/500',
    available: true,
    tags: ['clipado', 'embutidos']
  },
  {
    id: 6,
    title: 'Embutidora Neumática GQD30',
    category: 'Maquinaria Industrial China',
    subcategory: 'Embutidoras',
    brand: 'GQD',
    origin: 'China',
    condition: 'Nueva',
    description: 'Tolva de 30L ideal para pequeñas y medianas empresas del rubro alimentario.',
    image: 'https://picsum.photos/seed/gqd30/700/500',
    available: true,
    capacity: '30 L',
    tags: ['embutidos', 'pyme']
  },
  {
    id: 7,
    title: 'Embutidora de Pistón SF-260',
    category: 'Maquinaria Industrial China',
    subcategory: 'Embutidoras',
    brand: 'SF',
    origin: 'China',
    condition: 'Nueva',
    description: 'Equipo de pistón para producción de embutidos con excelente estabilidad de flujo.',
    image: 'https://picsum.photos/seed/sf260/700/500',
    available: true,
    capacity: '400 kg/h',
    power: '750 W',
    tags: ['embutidos', 'pistón']
  },
  {
    id: 8,
    title: 'Tumbler SZ-2000',
    category: 'Maquinaria Industrial China',
    subcategory: 'Marinado y Masajeo',
    brand: 'SZ',
    origin: 'China',
    condition: 'Nueva',
    description: 'Sistema para fabricación de jamón con gran capacidad para lotes industriales.',
    image: 'https://picsum.photos/seed/sz2000/700/500',
    available: false,
    capacity: '1500 kg / 2000 L',
    tags: ['jamón', 'tumbler']
  },
  {
    id: 9,
    title: 'Cutter Industrial 80L',
    category: 'Maquinaria Industrial China',
    subcategory: 'Cutter',
    brand: 'Industrial Cutter',
    origin: 'China',
    condition: 'Nueva',
    description: 'Emulsificación y corte fino en acero inoxidable para pastas cárnicas.',
    image: 'https://picsum.photos/seed/cutter80/700/500',
    available: true,
    capacity: '80 L',
    tags: ['emulsión', 'cárnico']
  },
  {
    id: 10,
    title: 'Molino 250AJR',
    category: 'Maquinaria Industrial China',
    subcategory: 'Molinos',
    brand: 'AJR',
    origin: 'China',
    condition: 'Nueva',
    description: 'Molino para carne congelada y fresca para líneas de alta demanda.',
    image: 'https://picsum.photos/seed/molino250ajr/700/500',
    available: true,
    capacity: 'Hasta 8,000 kg/h (fresco)',
    tags: ['molino', 'congelado']
  },
  {
    id: 11,
    title: 'Selladora al Vacío Doble Cámara',
    category: 'Maquinaria Industrial China',
    subcategory: 'Empaque y Conservación',
    brand: 'VacPack',
    origin: 'China',
    condition: 'Nueva',
    description: 'Empaque industrial de alta eficiencia para prolongar vida útil del producto.',
    image: 'https://picsum.photos/seed/doblecamera/700/500',
    available: true,
    tags: ['vacío', 'empaque']
  },
  {
    id: 12,
    title: 'Horno de Ahumado 4 Carros',
    category: 'Maquinaria Industrial China',
    subcategory: 'Hornos',
    brand: 'SmokeLine',
    origin: 'China',
    condition: 'Nueva',
    description: 'Horno para ahumado de salchichas, jamón y pollo en escala industrial.',
    image: 'https://picsum.photos/seed/horno4carros/700/500',
    available: false,
    capacity: '4 carros',
    tags: ['ahumado', 'hornos']
  },
  {
    id: 13,
    title: 'Generador Eléctrico 60KVA',
    category: 'Equipamiento Complementario',
    subcategory: 'Generadores',
    brand: 'PowerGen',
    origin: 'China',
    condition: 'Nueva',
    description: 'Generador tipo silencioso para respaldo de planta y continuidad operativa.',
    image: 'https://picsum.photos/seed/generador60/700/500',
    available: true,
    capacity: '60 KVA',
    tags: ['energía', 'respaldo']
  },
  {
    id: 14,
    title: 'Unidad de Refrigeración 20HP',
    category: 'Equipamiento Complementario',
    subcategory: 'Refrigeración',
    brand: 'ColdTech',
    origin: 'China',
    condition: 'Nueva',
    description: 'Solución de frío industrial para cavas y áreas de conservación.',
    image: 'https://picsum.photos/seed/refrigeracion20/700/500',
    available: true,
    power: '20 HP',
    tags: ['frío', 'cava cuarto']
  },
  {
    id: 15,
    title: 'Apilador Eléctrico 2000kg',
    category: 'Equipamiento Complementario',
    subcategory: 'Almacén',
    brand: 'LiftPro',
    origin: 'China',
    condition: 'Nueva',
    description: 'Equipo para manejo interno de carga con operación segura en almacenes.',
    image: 'https://picsum.photos/seed/apilador2000/700/500',
    available: true,
    capacity: '2000 kg',
    tags: ['logística', 'almacén']
  },
  {
    id: 16,
    title: 'Tripas de Colágeno',
    category: 'Materias Primas No Cárnicas',
    subcategory: 'Insumos para Embutidos',
    brand: 'FoodCasing',
    origin: 'Importado',
    condition: 'Nueva',
    description: 'Tripas para salchichas y jamones con excelente desempeño en proceso.',
    image: 'https://picsum.photos/seed/tripascolageno/700/500',
    available: true,
    tags: ['insumos', 'embutidos']
  },
  {
    id: 17,
    title: 'Carragenina Alimentaria',
    category: 'Materias Primas No Cárnicas',
    subcategory: 'Aditivos',
    brand: 'FoodAdd',
    origin: 'Importado',
    condition: 'Nueva',
    description: 'Aglutinante para mejorar textura y retención de agua en formulaciones.',
    image: 'https://picsum.photos/seed/carragenina/700/500',
    available: true,
    tags: ['aditivos', 'aglutinante']
  },
  {
    id: 18,
    title: 'Eritorbato de Sodio',
    category: 'Materias Primas No Cárnicas',
    subcategory: 'Aditivos',
    brand: 'FoodAdd',
    origin: 'Importado',
    condition: 'Nueva',
    description: 'Antioxidante para control de color y estabilidad en productos procesados.',
    image: 'https://picsum.photos/seed/eritorbato/700/500',
    available: true,
    tags: ['aditivos', 'antioxidante']
  }
];
